In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import datetime

import warnings
warnings.filterwarnings("ignore")

### Naive Bayes

In [23]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
yuanta_data = pd.read_csv('yuanta_vector.csv')
print(yuanta_data.shape)
print(yuanta_data['post_time'].describe())

yuanta_data = yuanta_data[yuanta_data['label'] != 0]

(8592, 20174)
count           8592
unique           481
top       2022-07-01
freq             117
Name: post_time, dtype: object


In [24]:
print(yuanta_data.shape)
print(yuanta_data['post_time'].describe())

(6091, 20174)
count           6091
unique           322
top       2022-07-01
freq             117
Name: post_time, dtype: object


In [10]:
yuanta_data.describe()

資產出           總營         滿手金融           深市          鴻智原  \
count  8592.000000  8592.000000  8592.000000  8592.000000  8592.000000   
mean      0.000116     0.000116     0.000116     0.000466     0.000116   
std       0.010788     0.010788     0.010788     0.021573     0.010788   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               沖心得          詮彩晶         益巴菲特           面像           聚愛  ...  \
count  8592.000000  8592.000000  8592.000000  8592.000000  8592.000000  ...   
mean      0.000116     0.000116     0.000116     0.000116     0.000116  ...   
std       0.010788     0.010788     0.010788     0.010788     0.010788  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              金虹彰銀          解惑請           粉紅         趨勢以上           腦正  \
count  8592.000000  8592.000000  8592.000000  8592.000000  8592.000000   
mean      0.000116     0.000233     0.000116     0.000233     0.000116   
std       0.010788     0.015256     0.010788     0.015256     0.010788   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               爆真心         股息宣告           重設           溜滑        label  
count  8592.000000  8592.000000  8592.000000  8592.000000  8592.000000  
mean      0.000116     0.000116     0.000233     0.000116    -0.024558  
std       0.010788     0.010788     0.015256     0.010788     0.841662  
min       0.000000     0.000000     0.000000     0.000000    -1.000000  
25%       0.000000     0.000000     0.000000     0.000000    -1.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     1.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 20173 columns]

In [58]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB 
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import train_test_split


prediction = pd.DataFrame(columns=['gnb_pred', 'mnb_pred', 'cnb_pred', 'bnb_pred', 'catnb_pred', 'true_label'])

X = yuanta_data.drop('label', axis=1)
y = yuanta_data['label']
X_train, X_validation, y_train, y_validation = train_test_split(X, y, test_size=0.2)

X_train = X_train.drop('post_time', axis=1)
X_validation = X_validation.drop('post_time', axis=1)

gnb = GaussianNB()
gnb.fit(X_train, y_train)
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
cnb = ComplementNB()
cnb.fit(X_train, y_train)
bnb = BernoulliNB()
bnb.fit(X_train, y_train)
catnb = CategoricalNB(min_categories=3)
catnb.fit(X_train, y_train)

for i in range(X_validation.shape[0]):
    print(i)
    gnb_y_pred = gnb.predict(X_validation.iloc[[i],:])
    mnb_y_pred = mnb.predict(X_validation.iloc[[i],:])
    cnb_y_pred = cnb.predict(X_validation.iloc[[i],:])
    bnb_y_pred = bnb.predict(X_validation.iloc[[i],:])
    catnb_y_pred = catnb.predict(X_validation.iloc[[i],:])
    prediction = pd.concat([prediction, pd.DataFrame([[gnb_y_pred, mnb_y_pred, cnb_y_pred, bnb_y_pred, catnb_y_pred, y_validation.iloc[i]]], columns=['gnb_pred', 'mnb_pred', 'cnb_pred', 'bnb_pred', 'catnb_pred', 'true_label'])], ignore_index=True)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [59]:
prediction

gnb_pred mnb_pred cnb_pred bnb_pred catnb_pred true_label
0        [-1]     [-1]     [-1]     [-1]       [-1]         -1
1        [-1]      [1]      [1]     [-1]       [-1]         -1
2        [-1]     [-1]     [-1]     [-1]       [-1]          1
3        [-1]     [-1]     [-1]     [-1]       [-1]         -1
4        [-1]     [-1]     [-1]     [-1]       [-1]         -1
...       ...      ...      ...      ...        ...        ...
1214     [-1]      [1]      [1]     [-1]       [-1]         -1
1215     [-1]     [-1]     [-1]     [-1]       [-1]          1
1216     [-1]     [-1]     [-1]     [-1]       [-1]         -1
1217     [-1]     [-1]     [-1]     [-1]       [-1]         -1
1218      [1]      [1]      [1]      [1]        [1]          1

[1219 rows x 6 columns]

In [64]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix
print('GaussianNB')
print("Accuracy: ", accuracy_score(list(prediction['true_label']), list(prediction['gnb_pred'])))
print(confusion_matrix(list(prediction['true_label']), list(prediction['gnb_pred']),labels=[1,-1]))
print("========================")
print('MultinomialNB')
print("Accuracy: ", accuracy_score(list(prediction['true_label']), list(prediction['mnb_pred'])))
print(confusion_matrix(list(prediction['true_label']), list(prediction['mnb_pred'])))
print("========================")
print('ComplementNB')
print("Accuracy: ", accuracy_score(list(prediction['true_label']), list(prediction['cnb_pred'])))
print(confusion_matrix(list(prediction['true_label']), list(prediction['cnb_pred'])))
print("========================")
print('BernoulliNB')
print("Accuracy: ", accuracy_score(list(prediction['true_label']), list(prediction['bnb_pred'])))
print(confusion_matrix(list(prediction['true_label']), list(prediction['bnb_pred'])))
print("========================")
print('CategoricalNB')
print("Accuracy: ", accuracy_score(list(prediction['true_label']), list(prediction['catnb_pred'])))
print(confusion_matrix(list(prediction['true_label']), list(prediction['catnb_pred'])))

GaussianNB
Accuracy:  0.6735028712059065
[[164 390]
 [  8 657]]
MultinomialNB
Accuracy:  0.6513535684987695
[[549 116]
 [309 245]]
ComplementNB
Accuracy:  0.6529942575881871
[[543 122]
 [301 253]]
BernoulliNB
Accuracy:  0.6505332239540607
[[613  52]
 [374 180]]
CategoricalNB
Accuracy:  0.6374077112387203
[[637  28]
 [414 140]]
